version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: pinggo-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: pinggo

  gateway:
    build: .
    container_name: pinggo-gateway
    restart: always
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=mongodb://mongodb:27017/pinggo
      - JWT_SECRET=pinggo_docker_secret_production_key_48291
    depends_on:
      - mongodb

volumes:
  mongo_data:
